### ISSUE TITLE
undefined 

### ISSUE THREAD

**Issue by OR1GG1N2** [imptype/serverless-chatgpt-discord-bot#1]
![image](https://github.com/imptype/serverless-chatgpt-discord-bot/assets/83551876/a4141122-5b77-4bc6-b5e1-0d48843b884c)
![image](https://github.com/imptype/serverless-chatgpt-discord-bot/assets/83551876/06617d1a-c779-4528-83c4-5a6112060b87)

**Comment by imptype** [comment]
@OR1GG1N2 You still leaked your bot's token by the way!! I hope you reset it by now. 

And sorry for the late reply, I thought this was that something you fixed by yourself already. I guess not though. See #2.
