### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by M4ketech** [imptype/serverless-chatgpt-discord-bot#2]
I checked all tokens and config files 5 times and still shows only this: 

![kuva](https://github.com/imptype/serverless-chatgpt-discord-bot/assets/8841448/ce97200a-ee64-452f-8486-5cfbf0d91740)

**Comment by imptype** [comment]
The code used in this repo might be outdated because it uses a commit
version of the `discohook` library from around 8 months ago. I'll add
versions to `requirements.txt` in a bit.

**Comment by imptype** [comment]
@M4ketech Fixed in the latest commit `770396e`. Git pull and update your packages!
